name: project_blackforest
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  cloud_firestore: ^3.4.4
  connectivity_plus: ^2.3.6+1
  lottie: ^1.4.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/